### ISSUE TITLE
Would it be possible to make bigger blueprint selections?

### ISSUE THREAD

**Issue by ghost** [FluffierThanThou/Blueprints#11]
I've noticed that the blueprints are selected with an invisible rectangle but it's size is constrained.
Would it be possible to make it bigger?

**Comment by FluffierThanThou** [comment]
This is a vanilla restriction on designators I'm afraid. I can take a quick look if it's doable to open this up (it might be simple, might be hardcoded). 

If I do take this on, I'll make a separate mini-mod, as this would apply to all designators, and it's not functionality strictly related to this mod.

**Comment by ghost** [comment]
Thanks for your time!

**Comment by FluffierThanThou** [comment]
it's hardcoded, I'm afraid. I'll leave this open for future reference, but it just got bumped down to a possible future side-project.
