### ISSUE TITLE
older blueprint dont correctly place power conduits in b18 

### ISSUE THREAD

**Issue by 10chaos1** [FluffierThanThou/Blueprints#14]
since the update for b18 when placing blueprints created in A16/A17 the blueprint often fails to place all power conduits in the blueprint here my output log : 
https://www.dropbox.com/s/va2d2sjgf463opk/output_log.txt?dl=0

and here is a image of the bug in game: 
http://steamcommunity.com/profiles/76561198065218003/screenshot/868495283639861366

also would you need the blueprint file?

**Comment by Karel-Kroeze** [comment]
Hi, thanks for the report. 

There is nothing immediately going wrong in the log, so there's not much I can say about that. It's also not immediately obvious to me what the problem is in the screenshot, all the power conduit blueprints appear to have been placed?

**Comment by 10chaos1** [comment]
i should have checked before posting (i was lacking sleep at the time ) after removing the mod i found out that this is a base game bug that sometimes colonists cancel a job when they shouldn't i'll report this sorry for wasting your time

**Comment by FluffierThanThou** [comment]
No worries, thanks for getting back to me!
