### ISSUE TITLE
"Blueprints" button messing menu order

### ISSUE THREAD

**Issue by NemoStein** [FluffierThanThou/Blueprints#15]
Currently, the `Blueprints` button is added in the middle of the `Architect` menu, messing the order or buttons (e.g.: the `Structure` button is now on the right column and the `Production` on the left, in the 3rd row).
This makes somewhat harder to find the buttons, because it's easier to remember the position of something instead the written text of it.

Is it possible to move the button to the end of the list (thus keeping the vanilla buttons in the original order)?
![image](https://user-images.githubusercontent.com/2738812/33796854-f64d6dfe-dce3-11e7-8f2e-392d1d76b759.png)

**Comment by mainettis** [comment]
I'd like to second this request.

It seems like it could easily be addressed by modifying the xml and moving to the bottom. Or, adding user configurable mod settings as per: https://rimworldwiki.com/wiki/Modding_Tutorials/ModSettings

I would be willing to do the work if this story is reopened 😁 

**Edit:**
Here is a sample of how it looks for me after simply modifying DesignationCategoriy_Blueprints.xml file `<order>20</order>`. It's my current workaround.
![20200305201154_1](https://user-images.githubusercontent.com/16723541/76044556-5baedc80-5f20-11ea-9ee0-dc1a84cd5144.jpg)
