### ISSUE TITLE
My blueprints keeps dissapearing when I restart the game, and there no debug error log. Thats really bad for me.

### ISSUE THREAD

**Issue by birb1849const** [FluffierThanThou/Blueprints#19]
My blueprints is dissapearing :c And I don't know why.

If want to do this there the steps:
1.Close the game.
2.Open the game
3.And Open your save.

Other mods

There 63 mod involved in my game, but they are not relacionated to blueprints.

Debug Log:
 
When the blueprint dissapear, there no debug error log.
  

Screenshots  
Ive made this blueprint: https://prnt.sc/oyukwy

And I restarted the game and it happened : https://prnt.sc/oyulah
 
My PC :
- OS: Windows 7 Ultimate
 - 32 bits
 
Game
   - 32 bits
 - DRM free
 - Version 1.0.2059

**Comment by FluffierThanThou** [comment]
Hi, thanks for the report. 

This has actually been implemented in an update a little while ago.
