### ISSUE TITLE
PortugueseBrazilian strings

### ISSUE THREAD

**Issue by rgponce** [FluffierThanThou/Blueprints#2]
[Translations.txt](https://github.com/FluffierThanThou/RW_Blueprints/files/573628/Translations.txt)

**Comment by FluffierThanThou** [comment]
thanks a bunch, added to the mod. 

I've added one more string in the update to A16, if you translate it for me I'll add that too;

`<Fluffy.Blueprints.NoStoredBlueprints>There are no exported blueprints (or they are all already loaded).</Fluffy.Blueprints.NoStoredBlueprints>`

**Comment by rgponce** [comment]
<Fluffy.Blueprints.NoStoredBlueprints>Não existem projetos exportados (ou eles todos já foram carregados).</Fluffy.Blueprints.NoStoredBlueprints>

**Comment by FluffierThanThou** [comment]
Added, will release tonight. Thanks!
