### ISSUE TITLE
1.1 compatibility

### ISSUE THREAD

**Issue by atroche** [FluffierThanThou/Blueprints#24]
The game currently gives these errors when run in 1.0:

<img width="745" alt="image" src="https://user-images.githubusercontent.com/29839/75137001-7de37600-573a-11ea-8c1a-e56cfb80a26e.png">

<img width="764" alt="image" src="https://user-images.githubusercontent.com/29839/75137035-95226380-573a-11ea-85e9-124b97b4605c.png">

**Comment by FluffierThanThou** [comment]
is this resolved with the new releases? If not, then I'm going to need more information. A full player_log would be a good start.
