### ISSUE TITLE
Bug/abuse-able blueprints

### ISSUE THREAD

**Issue by Ayrlixx** [FluffierThanThou/Blueprints#6]
Not sure if you know but it seems if you export a blueprint from a previous save with higher tech, start a new save as say tribals and then import the blueprints, you can actually craft items that you don't have the tech for.

Noticed this whilst building my hospital room and being able to build hospital beds right away and also being able to build the lamps without the power research etc.

**Comment by FluffierThanThou** [comment]
I need to add a check for this, thanks!
